import { IRbacRoleConfig, TRbacRole } from '../types';

export const STAFF_POLICIES: Partial<Record<TRbacRole, IRbacRoleConfig>> = {
  SUPERVISOR: {
    label: 'PIC Project',
    landingPage: '/',
    permissions: {
      DASHBOARD: 'CRUD',
      SUMMARY_REPORTS: 'CRUD',
      LOG_SHEETS: 'CRUD',
      WORK_REPORTS: 'CRUD',
      REPORTS: 'CRUD',
      LAB_ANALYSES: 'CRUD',
      ATTENDANCE: 'CRUD',
      PROJECTS_LIST: 'R',
      PROJECTS_ADMIN: '-',
      USERS_ADMIN: '-',
      CLIENTS: '-',
      CHEMICALS: 'R',
      PARAMETERS: 'R',
      MACHINES: 'R',
      NOTIFICATIONS: 'CRUD',
    },
  },
  TECHNICIAN: {
    label: 'Teknisi',
    landingPage: '/attendance',
    permissions: {
      DASHBOARD: 'R',
      SUMMARY_REPORTS: '-',
      LOG_SHEETS: 'CRU',
      WORK_REPORTS: 'CRU',
      REPORTS: 'R',
      LAB_ANALYSES: '-',
      ATTENDANCE: 'CRU',
      USERS_ADMIN: '-',
      PROJECTS_LIST: 'R',
      PROJECTS_ADMIN: '-',
      CLIENTS: '-',
      CHEMICALS: 'R',
      PARAMETERS: 'R',
      MACHINES: 'R',
      NOTIFICATIONS: 'CRUD',
    },
  },
  REPORTING: {
    label: 'Reporting',
    landingPage: '/summary-reports',
    permissions: {
      DASHBOARD: 'R',
      SUMMARY_REPORTS: 'CRU',
      LOG_SHEETS: 'CRU',
      WORK_REPORTS: 'CRU',
      REPORTS: 'CRU',
      LAB_ANALYSES: '-',
      ATTENDANCE: '-',
      USERS_ADMIN: '-',
      PROJECTS_LIST: 'R',
      PROJECTS_ADMIN: '-',
      CLIENTS: '-',
      CHEMICALS: 'R',
      PARAMETERS: 'R',
      MACHINES: 'R',
      NOTIFICATIONS: 'CRUD',
    },
  },
  DIRECTOR: {
    label: 'Direksi',
    landingPage: '/',
    permissions: {
      DASHBOARD: 'R',
      SUMMARY_REPORTS: 'R',
      LOG_SHEETS: 'R',
      WORK_REPORTS: 'R',
      REPORTS: 'R',
      LAB_ANALYSES: '-',
      ATTENDANCE: '-',
      USERS_ADMIN: '-',
      PROJECTS_LIST: 'R',
      PROJECTS_ADMIN: '-',
      CLIENTS: '-',
      CHEMICALS: 'R',
      PARAMETERS: 'R',
      MACHINES: 'R',
      NOTIFICATIONS: 'CRUD',
    },
  },
};
